= Apache Kafka / Kafka Connect / MQTT / Mosquitto Live Demo

Kai Waehner <kontakt@kai-waehner.de>
04 Sept 2018

This script assumes that all components (Kafka, Connect, MQTT Broker) use default values.

== Configuration

Configure MQTT Connector 

[source,bash]
----
TODO
----

== Starting backend services

_Make sure to have Confluent folder on PATH. Otherwise, go to `$CONFLUENT_INSTALL/bin` to execute commands these commands._

Start Kafka Connect and dependencies (Kafka, Zookeeper, Schema Registry): 

[source,bash]
----
confluent start kafka-connect
----

Create a topic for sensor reading: 

[source,bash]
----
kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic temperature
----

Start the MQTT Broker: 

[source,bash]
----
todo
----

TODO Use other Confluent-CLI commands like
confluent log connect
confluent current
cd ‘temp log directory’
less connect/connect.stderr
confluent list connectors
ls /Users/kai.waehner/confluent-5.0.0/etc


== Starting Client services

Send a MQTT message to the MQTT Broker, using `mosquitto_pub`: 

[source,bash]
----
mosquitto_pub -h 0.0.0.0 -p 1883 -t car/engine/temperature -q 2 -m "99999,2.10# 2.13# 2.19# 2.28# 2.44# 2.62# 2.80# 3.04# 3.36# 3.69# 3.97# 4.24# 4.53#4.80# 5.02# 5.21# 5.40# 5.57# 5.71# 5.79# 5.86# 5.92# 5.98# 6.02# 6.06# 6.08# 6.14# 6.18# 6.22# 6.27#6.32# 6.35# 6.38# 6.45# 6.49# 6.53# 6.57# 6.64# 6.70# 6.73# 6.78# 6.83# 6.88# 6.92# 6.94# 6.98# 7.01#7.03# 7.05# 7.06# 7.07# 7.08# 7.06# 7.04# 7.03# 6.99# 6.94# 6.88# 6.83# 6.77# 6.69# 6.60# 6.53# 6.45#6.36# 6.27# 6.19# 6.11# 6.03# 5.94# 5.88# 5.81# 5.75# 5.68# 5.62# 5.61# 5.54# 5.49# 5.45# 5.42# 5.38#5.34# 5.31# 5.30# 5.29# 5.26# 5.23# 5.23# 5.22# 5.20# 5.19# 5.18# 5.19# 5.17# 5.15# 5.14# 5.17# 5.16#5.15# 5.15# 5.15# 5.14# 5.14# 5.14# 5.15# 5.14# 5.14# 5.13# 5.15# 5.15# 5.15# 5.14# 5.16# 5.15# 5.15#5.14# 5.14# 5.15# 5.15# 5.14# 5.13# 5.14# 5.14# 5.11# 5.12# 5.12# 5.12# 5.09# 5.09# 5.09# 5.10# 5.08# 5.08# 5.08# 5.08# 5.06# 5.05# 5.06# 5.07# 5.05# 5.03# 5.03# 5.04# 5.03# 5.01# 5.01# 5.02# 5.01# 5.01#5.00# 5.00# 5.02# 5.01# 4.98# 5.00# 5.00# 5.00# 4.99# 5.00# 5.01# 5.02# 5.01# 5.03# 5.03# 5.02# 5.02#5.04# 5.04# 5.04# 5.02# 5.02# 5.01# 4.99# 4.98# 4.96# 4.96# 4.96# 4.94# 4.93# 4.93# 4.93# 4.93# 4.93# 5.02# 5.27# 5.80# 5.94# 5.58# 5.39# 5.32# 5.25# 5.21# 5.13# 4.97# 4.71# 4.39# 4.05# 3.69# 3.32# 3.05#2.99# 2.74# 2.61# 2.47# 2.35# 2.26# 2.20# 2.15# 2.10# 2.08"
----

You should see KSQL show another result from this new message. 

Use a CLI tool such as `kafka-console-consumer` from the shell prompt: 

[source,bash]
----
$ kafka-console-consumer --bootstrap-server localhost:9092 --topic ANOMALYDETECTIONWITHFILTER --from-beginning
99999,4.193955593608823
99999,5.363750640274894
99999,7.292092517069437
[...]
----

Now run a script to generate a stream of MQTT messages: 

[source,bash]
----
./sensor_generator.sh
----

== Stop services and destroy test data

Stop the sensor_generator script with Control-C. Then stop the backend services:

[source,bash]
----
brew services stop mosquitto
confluent destroy
----
